name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: File existence check
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "README.md, requirements.txt"
        allow_failure: true
        
    # - name: Failing step
    #   id: demo
    #   run: exit 1

    # - name: The demo step has failed
    #   if: ${{ failure() && steps.demo.conclusion == 'failure' }}
    #   run: echo 'Job failed'

        
        
